### ISSUE TITLE
MissingPluginException(No implementation found for method showToast on channel flutter_flexible_toast)

### ISSUE THREAD

**Issue by git-xbits** [sanket-vekariya/flutter_flexible_toast#1]
I getting error when I try use this plugin:

> [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method showToast on channel flutter_flexible_toast)
> #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
> <asynchronous suspension>
> #1      FlutterFlexibleToast.showToast (package:flutter_flexible_toast/flutter_flexible_toast.dart:109:31)
> <asynchronous suspension>
> #2      HomeIndexModel.getPosts.<anonymous closure> (package:PROJECTNAME/home/homeIndexModel.dart:76:30)
> #3      _rootRun (dart:async/zone.dart:1120:38)
> #4      _CustomZone.run (dart:async/zone.dart:1021:19)
> #5      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
> #6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
> #7      _rootRun (dart:async/zone.dart:1124:13)
> #8      _CustomZone.run (dart:async/zone.dart:1021:19)
> #9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
> #10     Timer._createTimer.<anonymous closure<…>

Flutter doctor -v

> [✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale pt-BR)
>     • Flutter version 1.9.1+hotfix.6 at /Users/phelipepalte/SDK/flutter
>     • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
>     • Engine revision b863200c37
>     • Dart version 2.5.0
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at /Users/phelipepalte/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.2
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.2.1, Build version 11B53
>     • CocoaPods version 1.8.4
> 
> [✓] Android Studio (version 3.5)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 41.0.2
>     • Dart plugin version 191.8593
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> 
> [!] VS Code (version 1.40.0)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     ✗ Flutter extension not installed; install from
>       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
> 
> [✓] Connected device (1 available)
>     • iPhone 8 Plus • 06DAFCAB-4DA9-41A4-B69A-8CAF0187C1A0 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)
> 
> ! Doctor found issues in 1 category.
>

**Comment by keremcankabadayi** [comment]
Check your class name. You can't be named `Toast`. That was my mistake :)

**Comment by sanket-vekariya** [comment]
The plugin is currently for android only...we will keep this in our criteria for next ios supported development in upcoming days...

**Comment by sanket-vekariya** [comment]
The plugin is currently for android only...we will keep this in our criteria for next ios supported development in upcoming days...
