### ISSUE TITLE
Duration option

### ISSUE THREAD

**Issue by keremcankabadayi** [sanket-vekariya/flutter_flexible_toast#2]
I couldn't find any duration param. Is there any plan for this?

**Comment by sanket-vekariya** [comment]
> I couldn't find any duration param. Is there any plan for this?

yes param is FlutterFlexibleToast.showToast(
        message: "Short Loading 2 Sec Toast",
        toastLength: Toast.LENGTH_LONG,
        toastGravity: ToastGravity.BOTTOM,
        icon: ICON.LOADING,
        radius: 100,
        elevation: 10,
        textColor: Colors.white,
        backgroundColor: Colors.black,
        timeInSeconds: 2);
