### ISSUE TITLE
How to adjust the size of icon? 

### ISSUE THREAD

**Issue by lanistor** [sanket-vekariya/flutter_flexible_toast#3]
How to adjust the size of icon?  It's a little big in iOS.

This's really a good library, don't rely on BuildContext, so we can use it anywhere. Thanks a lot.

**Comment by iosparesh** [comment]
> How to adjust the size of icon? It's a little big in iOS.
> 
> This's really a good library, don't rely on BuildContext, so we can use it anywhere. Thanks a lot.

Thanks that you like this plug-in,
Image size adjustment will be available in the next release.

**Comment by sanket-vekariya** [comment]
New Update:
We have added an optional "imageSize" parameter for controlling the leading image size now.
The issue is solved now and marking as "close".
