### ISSUE TITLE
Android ignores timeInSeconds param

### ISSUE THREAD

**Issue by fedotxxl** [sanket-vekariya/flutter_flexible_toast#7]
Param `timeInSeconds` doesn't work for param. Checked sources - `FlutterFlexibleToastPlugin.kt` - `time` value is not used. Please fix it

**Comment by MRishiK99** [comment]
is this fixed??

**Comment by fedotxxl** [comment]
I found that it's an Android limitation. Anyway, toasts look very weird on my Android... I gave up and replaced it with Snackbar
