### ISSUE TITLE
flutter_flexible_toast uses or overrides a deprecated API. Note: Recompile with -Xlint:deprecation for details.

### ISSUE THREAD

**Issue by kw2019ltd** [sanket-vekariya/flutter_flexible_toast#8]
Note: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_flexible_toast-0.1.4\android\src\main\kotlin\sanketvekariya\flutter_flexible_toast\GifImageView.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by imhasagi** [comment]
same here

**Comment by sanket-vekariya** [comment]
This warning is because of the class used to show gif is deprecated and another alternative is not available currently. This doesn't affect the output though.
